name: Portfolio CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django test
        run: |
          cd backend
          python manage.py test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to Docker Hub
        run : |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Backend Docker image
        run: docker build -f backend/Dockerfile -t "${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest" ./backend

      - name: Build Frontend Docker image
        run: docker build -f frontend/Dockerfile -t "${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest" ./frontend

      - name: Push Backend Docker image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest"

      - name: Push Frontend Docker image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest"